name: Build presentation
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 19
      uses: actions/setup-java@v3
      with:
        java-version: '19.0.0-beta+35.0.202208160349'
        distribution: 'adopt'
    - name: Compile Java code
      run: |
        cd src
        find -name "*.java" > sources.txt
        javac --source 19 --enable-preview @sources.txt
    - name: build presentation
      uses: xu-cheng/latex-action@v2
      with:
        root_file: document.tex
        working_directory: src
    - name: upload presentation
      uses: actions/upload-artifact@v2
      with:
        name: Presentation
        path: document.pdf